#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH=""
if [ -z "$BRANCH" ]; then
    echo "not on a branch"
    exit 1
fi;
UPSTREAM_BRANCH=$1
if [ -z "$UPSTREAM_BRANCH" ]; then
    UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
    if [ -z "$UPSTREAM_BRANCH" ]; then
        echo "$BRANCH does not have an upstream branch"
        exit 1
    fi;
fi;

echo "Comparing with $UPSTREAM_BRANCH"
git lg $BRANCH..$UPSTREAM_BRANCH $*