#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

git lg --all --author=$(git config user.email) --since='yesterday.11:00'