#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

echo deleting branch locally
if ! git branch -d "$1"; then
    exit 1
fi;

echo Deleting branch on all remotes
REMOTES=$(git remote)
while read -r line; do
    SHA=$(git show-ref --verify --quiet $remote/$branch)
    if [ -n "$SHA" ]; then
        REMOTE="${line#* }"
        if ! git push "$REMOTE" -d "$1"; then
            exit 1
        fi;
    fi;
done <<< "$REMOTES"