#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

if [ -d "$(git rev-parse --git-path rebase-merge)" ]; then
    git rebase --abort
    exit 0
elif [ -d "$(git rev-parse --git-path rebase-apply)" ]; then
    git rebase --abort
    exit 0
elif [ -f "$(git rev-parse --git-path MERGE_HEAD)" ]; then
    git merge --abort
    exit 0
elif [ -f "$(git rev-parse --git-path CHERRY_PICK_HEAD)" ]; then
    git cherry-pick --abort
    exit 0
elif [ -f "$(git rev-parse --git-path BISECT_START)" ]; then
    git bisect reset
    exit 0
fi

echo Unable to continue, unknown state
exit 1