#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

echo Fetching from all remotes
git fetch --all >/dev/null

echo Performing fast-forward on all work trees
WORK_TREES=$(git worktree list --porcelain | grep "^worktree ")
while read -r line; do
    WORK_TREE="${line#* }"
    cd $WORK_TREE
    BRANCH_REF="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH_REF=""
    if [ -z "$BRANCH_REF" ]; then
        echo "! $WORK_TREE not on a branch"
        continue
    fi;
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if ! [ -z "$(git status --porcelain)" ]; then
        echo "! $WORK_TREE not in a clean state"
        continue
    fi;
    UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
    if [ -z "$UPSTREAM_BRANCH" ]; then
        echo "! $WORK_TREE does not have an upstream branch"
        continue
    fi;
    echo "  $WORK_TREE [$BRANCH]"
    if ! git merge --ff-only >/dev/null 2>&1; then
        echo "  ! unable to fast forward, no upstream branch?"
    fi;
done <<< "$WORK_TREES"