#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

if [ -z "$1" ]; then
    BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH=""
    if [ -z "$BRANCH" ]; then
        echo "not on a branch"
        exit 1
    fi;
    UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
    if [ -z "$UPSTREAM_BRANCH" ]; then
        echo "$BRANCH does not have an upstream branch"
        exit 1
    fi;
    echo "Comparing with $UPSTREAM_BRANCH"
else
    if [ -z "$2"  ]; then
        BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH=""
        if [ -z "$BRANCH" ]; then
            echo "not on a branch"
            exit 1
        fi;
        UPSTREAM_BRANCH=$1
        echo "Comparing with $UPSTREAM_BRANCH"
    else
        BRANCH=$1
        UPSTREAM_BRANCH=$2
        echo "Comparing $BRANCH with $UPSTREAM_BRANCH"
    fi
fi;

git lg $UPSTREAM_BRANCH..$BRANCH $*