#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

for arg in "$@"
do
    if [[ "$arg" == -* ]]; then
        echo "Unknown option: $arg"
        exit 1
    else
        if [ -z "$BRANCH1" ]; then
            BRANCH1=$arg
        elif [ -z "$BRANCH2" ]; then
            BRANCH2=$arg
        else
            echo "Unknown argument: $arg"
            exit 1
        fi
    fi
done

if [ -z "$BRANCH1" ]; then
    BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null)" || BRANCH=""
    if [ -z "$BRANCH" ]; then
        echo "not on a branch"
        exit 1
    fi;
    UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
    if [ -z "$UPSTREAM_BRANCH" ]; then
        echo "$BRANCH does not have an upstream branch"
        exit 1
    fi;
    echo "Comparing with $UPSTREAM_BRANCH"
elif [ -z "$BRANCH2" ]; then
    BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null)" || BRANCH=""
    if [ -z "$BRANCH" ]; then
        echo "not on a branch"
        exit 1
    fi;
    UPSTREAM_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name $BRANCH1 2>/dev/null)
    if [ -z "$UPSTREAM_BRANCH" ]; then
        echo "$BRANCH does not have an upstream branch"
        exit 1
    fi;
    echo "Comparing with $UPSTREAM_BRANCH"
else
    BRANCH=$BRANCH1
    UPSTREAM_BRANCH=$BRANCH2
    echo "Comparing $BRANCH1 with $BRANCH2"
fi

BEHIND=$(git log $BRANCH..$UPSTREAM_BRANCH)
AHEAD=$(git log $UPSTREAM_BRANCH..$BRANCH)

set -- `git rev-list --left-right --count $UPSTREAM_BRANCH...$BRANCH`
BEHIND_COUNT="$1"
AHEAD_COUNT="$2"

BEHIND_ENDING="s"
AHEAD_ENDING="s"
if [ "$AHEAD_COUNT" -eq "1" ]; then
    AHEAD_ENDING=""
fi
if [ "$BEHIND_COUNT" -eq "1" ]; then
    BEHIND_ENDING=""
fi

if [ -z "$BEHIND" ]; then
    if [ -z "$AHEAD" ]; then
        echo ""
        echo "        +-- $BRANCH"
        echo "        v"
        echo "O---O---O        = $BRANCH is in sync with $UPSTREAM_BRANCH"
        echo "        ^"
        echo "        +-- $UPSTREAM_BRANCH"
        exit 0
    else
        echo ""
        echo "                +-- $BRANCH"
        echo "                v"
        echo "O---O---O- ... -O        = $BRANCH is $AHEAD_COUNT commit$AHEAD_ENDING ahead of $UPSTREAM_BRANCH"
        echo "        ^"
        echo "        +-- $UPSTREAM_BRANCH"
        exit 0
    fi;
else
    if [ -z "$AHEAD" ]; then
        echo ""
        echo "        +-- $BRANCH"
        echo "        v"
        echo "O---O---O- ... -O        = $UPSTREAM_BRANCH is $BEHIND_COUNT commit$BEHIND_ENDING ahead of $BRANCH"
        echo "                ^"
        echo "                +-- $UPSTREAM_BRANCH"
        exit 0
    else
        echo ""
        echo "                  +-- $BRANCH"
        echo "                  v"
        echo "           + ... -O        = $BRANCH is $AHEAD_COUNT commit$AHEAD_ENDING ahead of $UPSTREAM_BRANCH"
        echo "          /"
        echo "         /"
        echo "O---O---O"
        echo "         \\"
        echo "          \\"
        echo "           + ... -O        = $UPSTREAM_BRANCH is $BEHIND_COUNT commit$BEHIND_ENDING ahead of $BRANCH"
        echo "                  ^"
        echo "                  +-- $UPSTREAM_BRANCH"
        exit 0
    fi;
fi;