#!/bin/sh

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo error: not in a git repository or work tree
    exit 1
fi;

URL=$(git config --local integration.codereview)
if [ -z "$URL" ]; then
    echo "Use git config --local integration.codereview \"(url to code review web interface)\""
    echo "Add the keyword <BRANCH> with the brackets in place where the current branch name should be specified"
    exit 1
fi

BRANCH=$(git symbolic-ref HEAD)
BRANCH=${BRANCH#refs/heads/}
URL=${URL/<BRANCH>/$BRANCH}
start "$URL"